@startuml
left to right direction

actor "Cliente" as Cliente

rectangle "CLIENTE"{
    usecase "CRUDCliente" as UC1
    usecase "PedirOrcamento" as UC3
    usecase "FazerCompra" as UC8
    usecase "RealizarPagamento" as UC7
}
Cliente --> UC3
Cliente --> UC1
Cliente --> UC8
UC8 --> UC7:<<include>>

@enduml