@startuml
left to right direction

actor "Cliente" as Cliente

rectangle "CLIENTE"{
    usecase "ManterCliente" as UC1
    usecase "Venda" as UC8
    usecase "PedirOrcamento" as UC3
    usecase "Pagamento" as UC7
}
Cliente --> UC3
Cliente --> UC1
Cliente --> UC8 
UC8 --> UC7:<<include>>

@enduml