@startuml
left to right direction
actor "Fornecedor" as Fornecedor
rectangle "FORNECEDOR"{
    usecase "ManterFornecedor"as UC2
    usecase "Compra" as UC8
    usecase "Pagamento" as UC7
    usecase "Cotacao" as UC5  
}
Fornecedor --> UC2
Fornecedor --> UC5
Fornecedor --> UC8
UC8 --> UC7:<<include>>
@enduml