@startuml
left to right direction
actor "Fornecedor" as Fornecedor
rectangle "FORNECEDOR"{
    usecase "CRUDFornecedor"as UC2
    usecase "FazCotacao" as UC5
    usecase "RealizarVenda" as UC8
    usecase "RecebePagamento " as UC7

}
Fornecedor --> UC2
Fornecedor --> UC5
Fornecedor --> UC8
UC8 --> UC7:<<include>>
@enduml