@startuml

left to right direction
actor "MSV" as Msv

rectangle "MSV"{
    usecase "CRUDCliente" as UC1
    usecase "CRUDFornecedor"as UC2
    usecase "PedirOrcamento" as UC3
    usecase "RealizarCompra" as UC6
    usecase "Pagamento" as UC7
    usecase "RealizarVenda" as UC8
    usecase "FazCotacao" as UC5
    usecase "CRUDTransportadora" as UC9 
    usecase "CRUDProdutos" as UC4  
}


Msv --> UC1
Msv --> UC2
Msv --> UC3
Msv --> UC6
Msv --> UC8
Msv --> UC5
Msv --> UC9
Msv --> UC4

UC8 --> UC7:<<include>>
UC6 --> UC7:<<include>>
@enduml