@startuml
 
actor Cliente
actor MVS
boundary "Tela Cliente" as TC
entity "Pedido" as SI
actor Fornecedor

Cliente -> TC : seleciona produtos 
TC -> SI : solicita orçamento
SI-> Fornecedor: solicita cotacao ao fornecedor 
Fornecedor --> SI : retorna valores da cotacao
SI --> MVS : retorna valores
MVS --> Cliente : envia orcamento 
Cliente -> SI : aprova orcamento
SI--> Cliente: Solicita pagamento
Cliente -> SI :efetiva pagamento
MVS -> Fornecedor : faz pedido fornecedor
MVS -> Fornecedor: paga fornecedor
Fornecedor --> MVS : envia produtos
MVS-->Cliente :encaminha entrega ao cliente

@enduml